GET /apis/default/fhir/Patient HTTP/1.1
Host: localhost:9300
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ6dTYxTF9LdjRJeDI2eDlkdjdRSzY2eld2Nk1NYW5SOVprejg0OVpXMW9jIiwianRpIjoiNjc2MjFkM2I1MGU1MjY1NzE2YzA0NzVmZWYwMjkyNzVkNjJhY2I4OWQ5OTBjY2FlMWVlZTQwN2NmY2I1Mjc2MWZjNDIwMDg0MzliYWRlNGMiLCJpYXQiOjE3NDM4MDQzNDkuMjYzOTMzLCJuYmYiOjE3NDM4MDQzNDkuMjYzOTM2LCJleHAiOjE3NDM4MDQ2NDkuMjUzNDI4LCJzdWIiOiI5ZTk1OGY5Ny0yNDU0LTQ0ODUtODUxMC04YzliMzUzOTVkNTYiLCJzY29wZXMiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiLCJhcGk6b2VtciIsImFwaTpmaGlyIiwiYXBpOnBvcnQiLCJwYXRpZW50L1BhdGllbnQucmVhZCIsInN5c3RlbS9QYXRpZW50LnJlYWQiLCJzaXRlOmRlZmF1bHQiXX0.HX52BVk2DcEuk5n5SJjIBTi_n1cPFgwTsUEfy2VG0TeloTi0ypBqzOc8FihAxkvdCyMv09DawACSkfOa5fOkK4kO1DwsUsvRHOOvhsIlAyxLoj2rppd85JC3GxysNr2rw8-xQBlb4pGj-mqJSSmPZDeNZqlF505w2YytkNdbPcSzr3Qv7azrZXRvPZpyZ1Na1PbsxfsKlieJogZCvEsFixu30tdqTU06AtHCjA-tJ-tQsF8TUSqG6KWX2HErwBQwL1M3cMXiq9a_twBobGKzTiFm6o9O26qpA4Ig92nmsHiAWzhLqeGrTnJvUHC-3CZQoTHQXI_m2QtMaz1CDq0INQ